---
- hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Set the required variables
      set_fact:
        ingest_token: "{{ lookup('env','ACCESS_TOKEN') }}"
        rum_token: "{{ lookup('env','RUM_TOKEN') }}"
        realm: "{{ lookup('env','REALM') }}"
        instance: "{{ lookup('env','INSTANCE') }}"
        hec_url: "{{ lookup('env','HEC_URL') }}"
        hec_token: "{{ lookup('env','HEC_TOKEN') }}"

  tasks:
    - name: Configure Orbstack
      block:
      - name: Check to see if the config has run
        stat:
          path: /orange_rabbit.followed
        register: wh_result

      - name: Create K3s secrets YAML
        file:
          path: /home/splunk/splunk-k8s-secrets.yaml
          owner: splunk
          group: splunk
          state: touch
        become: true
        when: not wh_result.stat.exists

      - name: Update secrets YAML
        ansible.builtin.blockinfile:
          path: /home/splunk/splunk-k8s-secrets.yaml
          block: |
            apiVersion: v1
            kind: Secret
            metadata:
              name: splunk-secrets
              namespace: default
            type: Opaque
            stringData:
              app: {{ instance }}
              deployment: "deployment.environment={{ instance }}"
              instance: {{ instance }}
              realm: {{ realm }}
              rum_token: {{ rum_token }}
        become: true
        when: not wh_result.stat.exists

      - name: Apply secrets YAML
        command: kubectl apply -f splunk-k8s-secrets.yaml
        when: not wh_result.stat.exists

      - name: Create a file to signify that the config has run successfully
        file:
          path: "/orange_rabbit.followed"
          state: touch
        become: true
        when: not wh_result.stat.exists