apiVersion: apps/v1
kind: Deployment
metadata:
  name: doorgame
spec:
  selector:
    matchLabels:
      app: doorgame
  template:
    metadata:
      labels:
        app: doorgame
    spec:
      tolerations:
      nodeSelector:
      terminationGracePeriodSeconds: 5
      containers:
        - name: doorgame
          image: docker.io/library/doorgame:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9090
          env:
            - name: PORT
              value: "9090"
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(NODE_IP):4317"
            - name: OTEL_SERVICE_NAME
              value: "doorgame"
            - name: OTEL_PROPAGATORS
              value: "tracecontext,baggage"
            - name: SPLUNK_METRICS_ENABLED
              value: true
            - name: SPLUNK_METRICS_ENDPOINT
              value: "http://$(NODE_IP):9943"
            - name: SPLUNK_PROFILER_ENABLED
              value: true
            - name: SPLUNK_PROFILER_MEMORY_ENABLED
              value: true
          resources:
            requests:
              cpu: 110m
              memory: 90Mi
            limits:
              cpu: 130m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: doorgame
spec:
  type: ClusterIP
  selector:
    app: doorgame
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090