apiVersion: apps/v1
kind: Deployment
metadata:
  name: doorgame
spec:
  selector:
    matchLabels:
      app: doorgame
  template:
    metadata:
      labels:
        app: doorgame
    spec:
      tolerations:
      nodeSelector:
      terminationGracePeriodSeconds: 5
      containers:
        - name: doorgame
          image: docker.io/library/doorgame:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9090
          env:
            - name: PORT
              value: "9090"
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(NODE_IP):4317"
            - name: OTEL_SERVICE_NAME
              value: "doorgame"
            - name: OTEL_PROPAGATORS
              value: "tracecontext,baggage"
            - name: SPLUNK_METRICS_ENABLED
              value: "true"
            - name: SPLUNK_METRICS_ENDPOINT
              value: "http://$(NODE_IP):9943"
            - name: SPLUNK_PROFILER_ENABLED
              value: "false"
            - name: SPLUNK_PROFILER_MEMORY_ENABLED
              value: "false"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: MYSQL_ROOT_PASSWORD
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: doorgame
spec:
  type: LoadBalancer
  selector:
    app: doorgame
  ports:
    - protocol: TCP
      port: 81
      targetPort: 9090