name: 'Setup'
description: 'Setup build environment'

runs:
  using: "composite"
  steps:
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.110.0'
        extended: true

    - name: Setup yq
      uses: chrisdickinson/setup-yq@latest
      with:
        yq-version: '4.20.2'
        yq-url: 'https://github.com/mikefarah/yq/releases/download/v{version}/yq_{platform}_{arch}'

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Cache go dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/hugo_cache
        key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-hugomod-

#    - name: Get Submodules
#      shell: bash
#      run: cd themes/docsy && git submodule update -f --init --jobs=6 && cd ../..

