language: python
os: linux
dist: xenial
if: tag IS present
cache: pip
env:
  global:
  - secure: UO5PqUJh+Vx9GXLJhtM9meNLUCHMT95kWRWzH4hdnNISRnBqNpsoe2UvB/oFN8hZ7cvXDtLxHQZGQMzhT3gkAHA0+Z0SW2AY5SLn1iFvV5V5ELL//ORrDWsDginDFJxiegSqRO01nKEcORA+JlYccFLejoTpZV0GRz8Tj7te01nMPrfQjdUeIA8ho904BIYA/CLfNUeq8VXajB1fLG6pigRyepb3JvOYOBeYWQv+LSIbzAJrEOS0zxT388+uUt9YvssWRc+TmA8XNczfWNUc+wuFibTUzf6T67+YDtu2+haJS3dQtKGEB9jgx5Yaw1JKWf4pqkmFRCiUWn4c2kJrseWPTp7Br/98+q5HiveStC/p0p9+nG2tRTGOcrTK4iwm4czy22H4H34nlvnP1iZcWFQEY+9IcnZGyOcgiA2I608BPWWc/bbfaY5On8SBBEBeizdA900drMw89ojvykd6zf1B2+YmOYtJqyb+e/mbYW7MJNX3Jp0usyKGSLoh0xooq+EKsICaURrvC58enXpsaF57oTKVHc5BYI7NdW6dhPXgF7HKFmfHFl91yKYw5jwXXfvg5YREt/CpEtYBn5WqIsnD6VqVSNHZ7g746f5SBmAdD+LqTLqHdC+JcoT2NSj50gNsZMy+YE6QkbbyVOBn8/A2Rbdip8wkxpjNkr1HSfA=
  - secure: i+pf9R0omI+6Z4HiO9/qVYQyulxilmxMwkCRhaeY+xe826NuL1T6jQ6VZ0lhjeZYYui5NCyE3ePe5oZsABLWid4aAi0nd6h2MhPooWhZ5/hS4ik0Uf1TLa8ilD8y1+gOtsRQCi8VFJ92Osrp2hFyHI8O50Jd38RD2aCeHBypJ94lincxhIMR+1KGUQJWDApckhPZjBeTT2t0lnQErOBLqCRRpKU763iIx6/U1x6W75u1se60AJk+jqLIyFPOX+6+EYKF0iG+0enfVJpJ7U1uT+9UkCYGDpmQ5rTm1i9HXCHVuc6qMaq2/knHhJLm7l/ciaiLysNZy8pxl7GW5qJnlrx3kyGk8qZciYZwm/Qp2Y4JY24b724kYrZUWfpzclfD5YDxtIBkYbsoTvVRdLxDUmElomuQcLJy6/uYQ0jFeHYRaEnu/wLmS8gr8xMPLiHKfz7N9qt/b8mD19tjTYnLyiOJixHbZIOp7g/8fs3nLAy+7jTkezPLEgA0rILBMhUDFv+1rcVCDz4kjQyjQlyn9c/klSmM6Ef/qaY+7nYVyR7Hn5h5RtRxZru8IVbAIlmVjlYWmWo2s1vjajBKaFuslwUroVONUhhOuxcc7jCFwrYQiE20anR46wYt6i0xGMkyBzd8+Gwz1TqMjcM660kgrKdrOKUGb6GKbrhMmdUUTlc=
install:
- pip install -r requirements.txt
script:
- git clean -f -d -x
after_success:
- openssl aes-256-cbc -K $encrypted_0a58f67d178a_key -iv $encrypted_0a58f67d178a_iv
  -in o11y-workshop-deploy-key.enc -out o11y-workshop-deploy-key -d
- eval $(ssh-agent -s)
- chmod 600 o11y-workshop-deploy-key
- ssh-add ./o11y-workshop-deploy-key
- "./.ci/release.sh  || travis_terminate 1"
deploy:
  provider: script
  skip_cleanup: true
  script: "./.ci/deploy.sh"
  on:
    repo: signalfx/observability-workshop
    tags: true
