language: python
os: linux
dist: xenial
if: tag IS present
cache: pip
env:
  global:
    secure: U6r4b4BZZzLhu73RIKVL4YVncqgzC2GgYuuY7l+Jrc6WuF5L9OhMyEY8aOYWhdqDtvYEMk3iZQOWSxQR1os22Kr8wVM2sLqdZHeybxR/RRFNJ4bfKJwkqabkVBMlHcIjZO3hFqrGa7dVoxj63LOuEzB7qM0ZvcS3VZtFMS/f4Zi6QDzd485VRhv7B03VJ8aVSoHYqMx3gkpRwpAwOcOsrhwCmcEOHAcqMTV/6tt8vVl1jc8sy9YCDNhQmTdm0M2PfiYqv2FCfGJWkXOALjHtrloacgyRJZTwfVdbr/I9sSTN/sdzNv3QFTqErg3c6B+K+HDi61bi+R44ILmOA6wWFOz7nNUBUm1wVXBr5+ENpvQcRKGnIWiJvlCyna0DR7O3hklHFsEw80L5wipg1Xkr9VNflhoYd3RJxNMH7RQgY50KRTyVeIWg9StOQtsANR9wvmYPWT4uf0eGkaAcWfPOwGY+IFe0PzOZH/SByuOj6SG/EHHf9Lz4s2jdSwS/aN6PLvk1gL5TrOZL0v0oGDDzJXH+FJIfYl9FI/3nttJvqhns0yKO6MbXEcHYpZf+S6vlSzy1Pi6jQlgHZXMPE2Aa9EzRYiZXCUMQ4Nehbabbbyu+c2/TKVoWPN/zPCUwmci4J+sYe3/T7wcE/zxTpf0/5URRXurdz0IkhRDrsKZJTk0=
install:
- pip install -r requirements.txt
script:
- git clean -f -d -x
after_success:
- openssl aes-256-cbc -K $encrypted_0a58f67d178a_key -iv $encrypted_0a58f67d178a_iv
  -in o11y-workshop-deploy-key.enc -out o11y-workshop-deploy-key -d
- eval $(ssh-agent -s)
- chmod 600 o11y-workshop-deploy-key
- ssh-add ./o11y-workshop-deploy-key
- "./.ci/release.sh  || travis_terminate 1"
deploy:
  provider: script
  skip_cleanup: true
  script: "./.ci/deploy.sh"
  on:
    repo: signalfx/observability-workshop
    tags: true
