language: python
os: linux
dist: xenial
if: tag IS present
cache: pip
env:
  global:
install:
- pip install -r requirements.txt
script:
- git clean -f -d -x
after_success:
- eval $(ssh-agent -s)
- chmod 600 o11y-workshop-deploy-key
- ssh-add ./o11y-workshop-deploy-key
- "./.ci/release.sh  || travis_terminate 1"
deploy:
  provider: script
  skip_cleanup: true
  script: "./.ci/deploy.sh"
  on:
    repo: signalfx/observability-workshop
    tags: true
