---
# Source: splunk-otel-collector/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: default-otel-collector-agent
  namespace: default
  labels:
    app.kubernetes.io/name: otel-collector
    app: otel-collector
    component: otel-collector-agent
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: otel-collector
      release: default
  template:
    metadata:
      labels:
        app: otel-collector
        component: otel-collector-agent
        release: default
      annotations:
        checksum/config: 777574d73f3948712985d93f22b80f7fd878e5b96d08e33ca35a949b7c826943
        kubectl.kubernetes.io/default-container: otel-collector
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: default-otel-collector
      serviceAccountName: default-otel-collector
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
      containers:
      - name: otel-collector
        command:
        - /otelcol-contrib
        - --config=/conf/relay.yaml
        ports:
        - name: jaeger-grpc
          containerPort: 14250
          hostPort: 14250
          protocol: TCP
        - name: jaeger-thrift
          containerPort: 14268
          hostPort: 14268
          protocol: TCP
        - name: otlp
          containerPort: 4317
          hostPort: 4317
          protocol: TCP
        - name: otlp-http
          containerPort: 4318
          protocol: TCP
        - name: sfx-forwarder
          containerPort: 9080
          hostPort: 9080
          protocol: TCP
        - name: signalfx
          containerPort: 9943
          hostPort: 9943
          protocol: TCP
        - name: zipkin
          containerPort: 9411
          hostPort: 9411
          protocol: TCP
        image: otel/opentelemetry-collector-contrib
        imagePullPolicy: IfNotPresent
        env:
          - name: SPLUNK_MEMORY_TOTAL_MIB
            value: "500"
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: SPLUNK_API_URL
            valueFrom:
              configMapKeyRef:
                name: otel-configmap
                key: splunk_api_url
          - name: SPLUNK_INGEST_URL
            valueFrom:
              configMapKeyRef:
                name: otel-configmap
                key: splunk_ingest_url
          - name: K8S_CLUSTER_NAME
            valueFrom:
              configMapKeyRef:
                name: otel-configmap
                key: k8s_cluster_name
          - name: K8S_NODE_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: K8S_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: K8S_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: K8S_POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SPLUNK_OBSERVABILITY_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: default-otel-collector
                key: splunk_observability_access_token
          - name: SPLUNK_HEC_URL
            valueFrom:
              configMapKeyRef:
                name: otel-configmap
                key: splunk_hec_url
          - name: SPLUNK_HEC_TOKEN
            valueFrom:
              secretKeyRef:
                name: default-otel-collector
                key: splunk_hec_token
          - name: SPLUNK_INDEX
            valueFrom:
              configMapKeyRef:
                name: otel-configmap
                key: splunk_index
        readinessProbe:
          httpGet:
            path: /
            port: 13133
        livenessProbe:
          httpGet:
            path: /
            port: 13133
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /conf
          name: otel-configmap
        - mountPath: /hostfs/dev
          name: host-dev
          readOnly: true
        - mountPath: /hostfs/etc
          name: host-etc
          readOnly: true
        - mountPath: /hostfs/proc
          name: host-proc
          readOnly: true
        - mountPath: /hostfs/run/udev/data
          name: host-run-udev-data
          readOnly: true
        - mountPath: /hostfs/sys
          name: host-sys
          readOnly: true
        - mountPath: /hostfs/var/run/utmp
          name: host-var-run-utmp
          readOnly: true
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
      terminationGracePeriodSeconds: 600
      volumes:
      - name: host-dev
        hostPath:
          path: /dev
      - name: host-etc
        hostPath:
          path: /etc
      - name: host-proc
        hostPath:
          path: /proc
      - name: host-run-udev-data
        hostPath:
          path: /run/udev/data
      - name: host-sys
        hostPath:
          path: /sys
      - name: host-var-run-utmp
        hostPath:
          path: /var/run/utmp
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: otel-configmap
        configMap:
          name: default-otel-collector-otel-agent
          items:
            - key: relay
              path: relay.yaml
