---
# Source: splunk-otel-collector/templates/service-agent.yaml
apiVersion: v1
kind: Service
metadata:
  name: default-otel-collector-agent
  namespace: default
  labels:
    app.kubernetes.io/name: otel-collector
    app: otel-collector
    component: otel-collector-agent
    app.kubernetes.io/component: otel-collector-agent
spec:
  type: ClusterIP
  ports:
  - name: jaeger-grpc
    port: 14250
    targetPort: jaeger-grpc
    protocol: TCP
  - name: jaeger-thrift
    port: 14268
    targetPort: jaeger-thrift
    protocol: TCP
  - name: otlp
    port: 4317
    targetPort: otlp
    protocol: TCP
  - name: otlp-http
    port: 4318
    targetPort: otlp-http
    protocol: TCP
  - name: signalfx
    port: 9943
    targetPort: signalfx
    protocol: TCP
  - name: zipkin
    port: 9411
    targetPort: zipkin
    protocol: TCP
  selector:
    app: otel-collector
    component: otel-collector-agent
    release: default
  internalTrafficPolicy: Local
