---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: otel-contrib-collector
  namespace: default
  labels:
    app.kubernetes.io/name: otel-collector
    app: otel-collector
