---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - image: quay.io/phagen/spring-petclinic-config-server:0.0.1
          name: config-server
          imagePullPolicy: Always
          ports:
          - containerPort: 8888   
          env:

          - name: RUM_REALM
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: realm
          - name: RUM_AUTH
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: rum_token
          - name: RUM_APP_NAME
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: app
          - name: RUM_ENVIRONMENT
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: env
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: SIGNALFX_ENDPOINT_URL
            value: "http://$(NODE_IP):9411/api/v2/spans"
          - name: SIGNALFX_SERVER_TIMING_CONTEXT
            value: "true"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 800m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  type: ClusterIP
  selector:
    app: config-server
  ports:
  - name: tcp
    port: 8888
    targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - command:
            - ./dockerize
            - -wait=tcp://config-server:8888
            - -timeout=60s
            - --
            - java
            - org.springframework.boot.loader.JarLauncher
          image: quay.io/phagen/spring-petclinic-discovery-server:0.0.1
          name: discovery-server
          imagePullPolicy: Always
          ports:
          - containerPort: 8761  
          env:
  
          - name: RUM_REALM
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: realm
          - name: RUM_AUTH
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: rum_token
          - name: RUM_APP_NAME
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: app
          - name: RUM_ENVIRONMENT
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: env
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: SIGNALFX_ENDPOINT_URL
            value: "http://$(NODE_IP):9411/api/v2/spans"
          - name: SIGNALFX_SERVER_TIMING_CONTEXT
            value: "true"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 800m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  type: ClusterIP
  selector:
    app: discovery-server
  ports:
  - name: tcp
    port: 8761
    targetPort: 8761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - command:
            - ./dockerize
            - -wait=tcp://discovery-server:8761
            - -timeout=60s
            - --
            - java
            - org.springframework.boot.loader.JarLauncher
          name: api-gateway
          image: quay.io/phagen/spring-petclinic-api-gateway:0.0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
  
          - name: RUM_REALM
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: realm
          - name: RUM_AUTH
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: rum_token
          - name: RUM_APP_NAME
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: app
          - name: RUM_ENVIRONMENT
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: env
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: SIGNALFX_ENDPOINT_URL
            value: "http://$(NODE_IP):9411/api/v2/spans"
          - name: SIGNALFX_SERVER_TIMING_CONTEXT
            value: "true"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 800m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 82
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-external
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "3"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
    external-dns.alpha.kubernetes.io/hostname: demo.
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 81
    targetPort: 8080
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
spec:
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - command:
            - ./dockerize
            - -wait=tcp://discovery-server:8761
            - -timeout=60s
            - --
            - java
            - org.springframework.boot.loader.JarLauncher
          image: quay.io/phagen/spring-petclinic-customers-service:0.0.1
          name: customers-service
          imagePullPolicy: Always
          ports:
          - containerPort: 8081
          env:
  
          - name: RUM_REALM
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: realm
          - name: RUM_AUTH
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: rum_token
          - name: RUM_APP_NAME
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: app
          - name: RUM_ENVIRONMENT
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: env
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: SIGNALFX_ENDPOINT_URL
            value: "http://$(NODE_IP):9411/api/v2/spans"
          - name: SIGNALFX_SERVER_TIMING_CONTEXT
            value: "true"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 800m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
spec:
  type: ClusterIP
  selector:
    app: customers-service
  ports:
  - name: tcp
    port: 8081
    targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
spec:
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - command:
            - ./dockerize
            - -wait=tcp://discovery-server:8761
            - -timeout=60s
            - --
            - java
            - org.springframework.boot.loader.JarLauncher
          image: quay.io/phagen/spring-petclinic-vets-service:0.0.1
          name: vets-service
          imagePullPolicy: Always
          ports:
          - containerPort: 8083      
          env:

          - name: RUM_REALM
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: realm
          - name: RUM_AUTH
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: rum_token
          - name: RUM_APP_NAME
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: app
          - name: RUM_ENVIRONMENT
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: env
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: SIGNALFX_ENDPOINT_URL
            value: "http://$(NODE_IP):9411/api/v2/spans"
          - name: SIGNALFX_SERVER_TIMING_CONTEXT
            value: "true"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 800m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
spec:
  type: ClusterIP
  selector:
    app: vets-service
  ports:
  - name: tcp
    port: 8083
    targetPort: 8083  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
spec:
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - command:
            - ./dockerize
            - -wait=tcp://discovery-server:8761
            - -timeout=60s
            - --
            - java
            - org.springframework.boot.loader.JarLauncher
          image: quay.io/phagen/spring-petclinic-visits-service:0.0.1
          name: visits-service
          imagePullPolicy: Always
          ports:
          - containerPort: 8082      
          env:
 
          - name: RUM_REALM
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: realm
          - name: RUM_AUTH
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: rum_token
          - name: RUM_APP_NAME
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: app
          - name: RUM_ENVIRONMENT
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: env
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: SIGNALFX_ENDPOINT_URL
            value: "http://$(NODE_IP):9411/api/v2/spans"
          - name: SIGNALFX_SERVER_TIMING_CONTEXT
            value: "true"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 800m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
spec:
  type: ClusterIP
  selector:
    app: visits-service
  ports:
  - name: tcp
    port: 8082
    targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
spec:
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - command:
            - ./dockerize
            - -wait=tcp://discovery-server:8761
            - -timeout=60s
            - --
            - java
            - org.springframework.boot.loader.JarLauncher
          image: quay.io/phagen/spring-petclinic-admin-server:0.0.1
          name: admin-server
          imagePullPolicy: Always
          ports:
          - containerPort: 9090   
          env:
 
          - name: RUM_REALM
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: realm
          - name: RUM_AUTH
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: rum_token
          - name: RUM_APP_NAME
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: app
          - name: RUM_ENVIRONMENT
            valueFrom:
              secretKeyRef:
                name: workshop-secret
                key: env
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: SIGNALFX_ENDPOINT_URL
            value: "http://$(NODE_IP):9411/api/v2/spans"
          - name: SIGNALFX_SERVER_TIMING_CONTEXT
            value: "true"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 800m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
spec:
  type: ClusterIP
  selector:
    app: admin-server
  ports:
  - name: tcp
    port: 9090
    targetPort: 9090           