apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: opentelemetry-demo-frontendproxy
  ports:
  - name: http
    port: 81
    targetPort: 8080