apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: config-server
    app.kubernetes.io/part-of: spring-petclinic
  name: spring-petclinic-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/spring-petclinic-default: "true"
        io.kompose.service: config-server
        app.kubernetes.io/part-of: spring-petclinic
    spec:
      containers:
        - image: springcommunity/spring-petclinic-config-server
          name: config-server
          ports:
            - containerPort: 8888
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
            #  cpu: "1"
              memory: 512Mi   
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: config-server
    app.kubernetes.io/part-of: spring-petclinic
  name: config-server
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    io.kompose.service: config-server
status:
  loadBalancer: {}
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: discovery-server
    app.kubernetes.io/part-of: spring-petclinic
  name: spring-petclinic-discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discovery-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/spring-petclinic-default: "true"
        io.kompose.service: discovery-server
        app.kubernetes.io/part-of: spring-petclinic
    spec:
      containers:
        - command:
            - ./dockerize
            - -wait=tcp://config-server:8888
            - -timeout=60s
            - --
            - java
            - org.springframework.boot.loader.JarLauncher
          image: springcommunity/spring-petclinic-discovery-server
          name: discovery-server
          ports:
            - containerPort: 8761
          resources:
            requests:
              cpu: 500m
              memory: 750Mi
            limits:
              #cpu: "1"
              memory: 800Mi   
      restartPolicy: Always
status: {}  
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: discovery-server
    app.kubernetes.io/part-of: spring-petclinic
  name: discovery-server
spec:
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
  selector:
    io.kompose.service: discovery-server
status:
  loadBalancer: {}
---