agent:
  config:
    exporters:
      signalfx:
        access_token: ${SPLUNK_OBSERVABILITY_ACCESS_TOKEN}
        api_url: "https://api.eu0.signalfx.com"
        ingest_url: "https://ingest.eu0.signalfx.com"
        sync_host_metadata: true
        correlation:
        send_otlp_histograms: true
    processors:
      resource/envname:
        attributes:
        - action: insert
          key: deployment.environment
          value: {{environment}}
    service:
      pipelines:
        traces:
          processors:
          - memory_limiter
          - k8sattributes
          - batch
          - resourcedetection
          - resource
          - resource/envname
