apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditcheckservice
spec:
  selector:
    matchLabels:
      app: creditcheckservice
  template:
    metadata:
      labels:
        app: creditcheckservice
    spec:
      tolerations:
      nodeSelector:
      terminationGracePeriodSeconds: 5
      containers:
      - name: creditcheckservice
        image: docker.io/library/credit-check-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8888
        env:
        - name: PORT
          value: "8888"
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(NODE_IP):4318"
        - name: OTEL_LOGS_EXPORTER
          value: "none"
        - name: OTEL_SERVICE_NAME
          value: "creditcheckservice"
        - name: SPLUNK_PROFILER_ENABLED
          value: "true"
        - name: SPLUNK_PROFILER_MEMORY_ENABLED
          value: "true"
        resources:
          requests:
            cpu: 500m
            memory: 190Mi
          limits:
            cpu: 800m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: creditcheckservice
spec:
  type: ClusterIP
  selector:
    app: creditcheckservice
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
