name: Build and Deploy O11y Cloud Workshop

# Controls when the action will run. Triggers manually
on: workflow_dispatch

jobs:
  build:
    name: Build and Deploy Workshop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Bumpversion and deploy using mike
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git pull
          FLAVOUR=minor
          TAG=$(bumpversion --list "$FLAVOUR" | awk -F= '/new_version=/ { print $2 }')
          awk "/Latest versions of the workshop are:/ { print; print \"- [v$TAG](https://signalfx.github.io/observability-workshop/v$TAG/)\";next }1" README.md |
          awk "NR==1,/Latest versions of the workshop are:/{c=3} c&&c-- " > README.new.md
          mv README.new.md README.md          
          git fetch --tags origin
          git add README.md
          git commit --amend -m "Releasing v$TAG"
          git tag -a "v$TAG" -m "Version $TAG"
          git push origin master || { echo 'Push failed. git pull --rebase from upstream and attempt another release.'; exit 1; }
          git push --tags          
          mike deploy --push "v$TAG" latest -u
