name: Build and Release Loadgen

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Loadgen Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build Loadgen
        run: |
          cd workshop/ninja/advanced-otel/loadgen/
          go build -o loadgen loadgen.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: loadgen-binary
          path: workshop/ninja/advanced-otel/loadgen/loadgen

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: loadgen-binary
          path: ./

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./loadgen
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
